name: Execute Python Scripts

on:
  push:
    branches:
      - main
      - devel

jobs:
  execute-scripts:
    name: Execute Python Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cssrlib-data repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies from cssrlib-data repository
        run: pip install -r requirements.txt

      - name: Get branch name
        id: get_branch_name
        run: echo "branch_name=$(basename $GITHUB_REF)" >> $GITHUB_OUTPUT

      - name: Clone cssrlib repository
        run: git clone -b ${{ steps.get_branch_name.outputs.branch_name }} https://github.com/${{ github.actor }}/cssrlib.git
        
      - name: Install dependencies from cssrlib repository
        run: |
          cd cssrlib
          pip install -r requirements.txt

      - name: Install dependencies for IGS file donwload
        run: sudo apt-get update && sudo apt-get install -y lftp gzip ncompress

      - name: Download IGS files
        run: |
          cd ./data
          while IFS=' ' read -r folder url; do
            [[ -z "$folder" || -z "$url" || "$folder" == "#" ]] && continue  # Skip empty lines and comments

            echo "Downloading $url to $folder/..."


            mkdir -p "$folder"  # Ensure destination folder exists
            file_name=$(basename "$url")  # Extract file name from URL
            dest_file="$folder/$file_name"  # Full path to downloaded file

            lftp -c "
              set ftp:passive-mode yes;
              open $(dirname "$url");
              cd $(dirname "$url" | cut -d'/' -f3-);
              mget -E $(basename "$url") -o $dest_file;
              bye"

            # Decompress if needed
            if [[ "$dest_file" == *.gz ]]; then
              echo "Decompressing $dest_file..."
              gunzip -f "$dest_file"  # Decompress in place
            elif [[ "$dest_file" == *.Z ]]; then
              echo "Decompressing $dest_file..."
              uncompress -f "$dest_file"  # Decompress in place
            fi

          done < igs_files.txt

      - name: Execute Python scripts
        run: |
          export PYTHONPATH="../cssrlib/src:$PYTHONPATH"
          cd ./samples
          for file in $(find . -name "*.py"); do
            if [ "$file" == "./igs_download.py" ]; then continue; fi
            echo "# Execute $file"
            echo "#"
            python "$file" > /dev/null
            echo "# ...done!"
            echo "#"
            echo
          done
